### PR TITLE
fix: updated smithy-client instrumentation to properly handle all types of clients for dynamo, sqs, sns

### LINKED ISSUE #208: AWS SDK v3 DynamoDB - newrelic@11.0.0 (v7.0.0 of this lib) no longer record DynamoDB on Databases APM tab
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

- See detailed notes and reproducible example here: https://github.com/pwrdrvr/dynamodb-session-store/pull/19
- DynamoDB access using `newrelic@10.4.0` logs DB access on the Database tab of APM, logging the specific operations, rates, and times
- DynamoDB access using `newrelic@11.0.0` logs DB access only as External Services of APM
- This PR appears to be a candidate of why this changed (but does not note this as intentional) as it removed the `lib-dynamodb` and `client-dynamodb` instrumentation and shifted the responsibility entirely to `smithy-client`: https://github.com/newrelic/node-newrelic-aws-sdk/pull/205

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT share sensitive information, whether personal, proprietary, or otherwise! )

## Expected Behavior

- DynamoDB access should be logged in detail on the Database tab of APM

[NOTE]: # ( Tell us what you expected to happen. )

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

- See full details and logs: https://github.com/pwrdrvr/dynamodb-session-store/pull/19

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce

- See full reproduction steps and code on an open source project that demos this: https://github.com/pwrdrvr/dynamodb-session-store/pull/19

[NOTE]: # ( Please be as specific as possible. )
[TIP]:  # ( Link a sample application that demonstrates the issue. )

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

* Node version: 16.17.1
* Operating System and version: Mac OS X and `node:18.17-alpine3.18` Docker image

## Additional context

[TIP]:  # ( Add any other context about the problem here. For example, relevant community posts or support tickets. )

### PR DESCRIPTION
**Pull request by bizob2828**
## Proposed Release Notes
 * Updated v3 smithy-client instrumentation to properly handle all types of clients for DynamoDB, SQS, and SNS. 

## Links
Closes #208

## Details
When the instrumentation was ported in #205 to only register relevant middleware if the client sending matched `this.constructor.name`.  This provided gaps because all the libraries we instrument: `@aws-sdk/client-sns`, `@aws-sdk/client-sqs`, `@aws-sdk/client-dynamodb`, `@aws-sdk/lib-dynamodb` have other classes that were not getting matched.  This updates the matching by stripping `Client` from the end of every constructor.

### CODE REVIEW

File: lib/v3/smithy-client.js [hunk 1]
```diff
@@ -29,7 +29,11 @@ module.exports = function instrumentSmithyClient(shim, smithyClientExport) {
 
 function wrapSend(shim, send) {
   return function wrappedSend() {
-    const client = this?.constructor?.name
+    // most clients we want to instrument aside from smithy-client
+    // extend themselves to provide different names(i.e. - SNS and SNSClient)
+    // we want to handle these the same by registering the sns middleware
+    const client = this.constructor.name.replace(/Client$/, '')
```
Comment (mrickard) [inline lib/v3/smithy-client.js:35]: Is there a scenario in which we'd want to reference the `this.constructor.name` properties defensively, like the previous version?

Comment (bizob2828) [reply lib/v3/smithy-client.js:35]: This was unnecessary

**Review by mrickard — APPROVED** [review]
