### PR TITLE
Fix presigned url workflow

### LINKED ISSUE #176: Unable to use AWS presigned urls with agent
## Description
When using the latest version of our agent, presigned urls can be generated, but cannot be used. When using the repro app, if you disable the agent, you are able to use a presigned url just fine. With the agent, you'll get an error that looks like this:
```
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
...
</Error>

```

## Expected Behavior
Presigned URLs are usable regardless of whether or not the agent is loaded

## Steps to Reproduce
https://github.com/jmartin4563/aws-sdk-bug

## Additional context
Originally reported in https://github.com/newrelic/node-newrelic/issues/1549#issuecomment-1485054979
This is caused by the changes we made for https://github.com/newrelic/node-newrelic-aws-sdk/issues/168, where we used to use a Symbol, which was transparent to the SDK, but due to changes in aws-sdk and a maintainer's suggestion, we switched to using a string header.

### PR DESCRIPTION
**Pull request by jmartin4563**
## Proposed Release Notes
* Fixed issue where agent instrumentation caused unusable presigned urls to be generated by `@aws-sdk/s3-request-presigner`

## Links
Closes #176 

## Details
This fix is a bit nuanced, and assumes you're a bit familiar with how [Middleware Stacks](https://aws.amazon.com/blogs/developer/middleware-stack-modular-aws-sdk-js/) work in the `@aws-sdk` ecosystem.

Specifically, using the `build` phase of middleware meant that we accidentally marked our `x-new-relic-disable-dt` header to be considered a Signed Header in the presigned url generation process, and signed headers have to be passed when using the generated presigned url. This is because `generateSignedURL` uses Commands as an input, and Commands have to be translated into HTTP Request structures, which happens as a `build` phase. However, the actual HTTP request happens outside the SDK, so customers would have had to start sending our header along with the HTTP call using the presigned url.

None of this was a problem when we used a Symbol, because Symbols are not iterable. However, due to another AWS bug and one of their maintainer's suggestion, we switched to using a string based header, which exposed a (now fixed) issue with `@aws-sdk/client-s3` and this issue with `@aws-sdk/s3-request-presigneer`.

Additionally, after talking with @bizob2828, I've added the ability to write/run smoke tests in this repo. Specifically, the reasoning for this is that our versioned tests stub out the actual AWS communications, which caused us to not catch several issues related to the changes we made to remove our disable DT Symbol from any service headers. These smoke tests still use the agent generated from our test utility functions, but requires live and accessible AWS assets.

An example run of the GitHub Action workflow can be found [here](https://github.com/newrelic/node-newrelic-aws-sdk/actions/runs/4577213339/jobs/8082353186).

Confirming the fix is easy now with these smoke tests, all you'll have to do is undo my change, run the tests, and observe the presigned URL tests failing due to an HTTP 403.

You can also use https://github.com/jmartin4563/aws-sdk-bug to manually test this fix.

### CODE REVIEW

File: lib/v3/smithy-client.js [hunk 1]
```diff
@@ -30,10 +30,24 @@ module.exports = function instrumentSmithyClient(shim, name, resolvedName) {
 function getPlugin(shim, config) {
   return {
     applyToStack: (clientStack) => {
+      /*
+       * `finalizeRequest` only happens when an actual HTTP request
+       * is to be sent over the wire. This used to use the `build` step,
+       * but that caused headaches with using Presigned URLs, which
+       * leverages the `build` step in it's logic. This caused x-new-relic-disable-dt
```
Comment (mrickard) [inline lib/v3/smithy-client.js:37]:
```suggestion
       * leverages the `build` step in its logic. This caused x-new-relic-disable-dt
```

File: lib/v3/smithy-client.js [hunk 2]
```diff
@@ -30,10 +30,24 @@ module.exports = function instrumentSmithyClient(shim, name, resolvedName) {
...
+       * to be added as a Signed Header to the Presigned URL, which broke customers
```
Comment (mrickard) [inline lib/v3/smithy-client.js:38]:
```suggestion
       * to be added as a Signed Header to the Presigned URL, which broke customers' code
```

**Review by mrickard — APPROVED** [review]
