### PR TITLE
fix: Updated aws-sdk v3 instrumentation to only call `shim.setLibrary` and `shim.setDatastore` once instead of on every call to sqs/sns/dyanmodb

### LINKED ISSUE #218: Memory exhaustion in newrelic/lib/util/logger.js when using @aws-sdk/client-sqs
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
After updating newrelic to version 11.6.0 client we faced with memory leaks issues in our code that uses @aws-sdk/client-sqs.
I've created a [repository](https://github.com/yehor-manzhula/newrelic-memory-leak) with an example that reproduces the issue we faced. (Please follow readme.me to startup project)

Right after test script `./run.sh ./src/aws-sdk-gc.js` is started memory starts rasing dramatically fast.
I've analyze the heapdumps and found that there are bunch of identical object being added in the snapshot comparison that route me to newrelic/lib/util/logger.js (see screenshots)

newrelic logger memory leak

## Expected Behavior
Memory will be cleaned with GC.

## [Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results

[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

## Steps to Reproduce
1. Clone example [repository](https://github.com/yehor-manzhula/newrelic-memory-leak) 
2. Follow readme.md
3. Run test script `./run.sh ./src/aws-sdk-gc.js`

## Your Environment
* ex: Node version: 20.10.0
* ex: Operating System and version: Linux Ubuntu 22.04.3 LTS

### PR DESCRIPTION
**Pull request by bizob2828**
## Proposed Release Notes
 * Updated aws-sdk v3 instrumentation to only call `shim.setLibrary` and `shim.setDatastore` once instead of on every call to SQS, SNS, and DynamoDB.

## Links
Closes #218

## Details
You can see the details from my analysis [here](https://github.com/newrelic/node-newrelic-aws-sdk/issues/218#issuecomment-1843329089). Big thanks to @jsumners-nr for pointing me in the right direction from the start. It made for a quick fix, the tests were the tricky part. If you undid the code side the tests would fail as the relevant `setLibrary` or `setDatastore` would be called n times vs just once.

### CODE REVIEW

File: lib/v3/dynamodb.js [hunk 1]
```diff
@@ -72,6 +71,9 @@ function dynamoMiddleware(shim, config, next, context) {
 
 const dynamoMiddlewareConfig = {
   middleware: dynamoMiddleware,
+  init(shim) {
+    shim.setDatastore(shim.DYNAMODB)
+  },
```
Comment (jsumners-nr) [inline lib/v3/dynamodb.js:76]: Codecov is suggesting that none of these new `init` methods are covered. Is that an issue?

Comment (bizob2828) [reply lib/v3/dynamodb.js:76]: @mrickard mentioned that too. I don't see it, where do you see that? The tests I wrote prove the init code. If you restore the code to the shim.setLibrary etc the tests will fail.

Comment (jsumners-nr) [reply lib/v3/dynamodb.js:76]: image
